# Generated by Django 5.0.4 on 2024-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_detail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("referral_code", models.CharField(max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
