# Generated by Django 5.0.4 on 2024-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_detail_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_detail",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="user_detail",
            table="User_info",
        ),
    ]
