# Generated by Django 5.0.4 on 2024-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_user_detail_points_alter_user_detail_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_detail",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
